//! Generate typed requests, events, and enums from `protocol.json`.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::PathBuf;
use std::process::Command;

use serde::Deserialize;
use serde_json::Value;

const HEADER: &str = "// @generated by `cargo xtask codegen` from protocol/protocol.json. Do not edit.\n\n#![allow(\n    clippy::large_enum_variant,\n    clippy::redundant_field_names,\n    clippy::struct_excessive_bools,\n    clippy::too_many_arguments,\n    rustdoc::bare_urls\n)]\n\n";

const FLOAT_FIELDS: &[&str] = &[
    "activeFps",
    "availableDiskSpace",
    "averageFrameRenderTime",
    "cpuUsage",
    "inputAudioBalance",
    "inputVolumeDb",
    "inputVolumeMul",
    "memoryUsage",
    "outputCongestion",
    "transitionCursor",
];

#[derive(Debug, Deserialize)]
pub struct Protocol {
    pub enums: Vec<ProtocolEnum>,
    pub requests: Vec<ProtocolRequest>,
    pub events: Vec<ProtocolEvent>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProtocolEnum {
    pub enum_type: String,
    pub enum_identifiers: Vec<ProtocolEnumId>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProtocolEnumId {
    #[serde(default)]
    pub description: String,
    pub enum_identifier: String,
    #[serde(default)]
    pub deprecated: bool,
    #[serde(default)]
    #[allow(dead_code)]
    pub initial_version: String,
    pub enum_value: Value,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProtocolRequest {
    pub description: String,
    pub request_type: String,
    #[serde(default)]
    pub rpc_version: String,
    #[serde(default)]
    pub deprecated: bool,
    pub initial_version: String,
    pub category: String,
    #[serde(default)]
    pub request_fields: Vec<ProtocolField>,
    #[serde(default)]
    pub response_fields: Vec<ProtocolField>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProtocolEvent {
    pub description: String,
    pub event_type: String,
    #[serde(default)]
    pub event_subscription: String,
    #[serde(default)]
    pub deprecated: bool,
    pub initial_version: String,
    pub category: String,
    #[serde(default)]
    pub data_fields: Vec<ProtocolField>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProtocolField {
    pub value_name: String,
    pub value_type: String,
    #[serde(default)]
    pub value_description: String,
    #[serde(default)]
    pub value_optional: bool,
    #[serde(default)]
    pub value_restrictions: Option<String>,
    #[serde(default)]
    pub value_optional_behavior: Option<String>,
}

#[derive(Debug, Deserialize, Default)]
pub struct Overrides {
    #[serde(default, rename = "alias")]
    pub aliases: Vec<AliasDef>,
    #[serde(default, rename = "struct")]
    pub structs: Vec<StructDef>,
    #[serde(default)]
    pub fields: BTreeMap<String, String>,
}

#[derive(Debug, Deserialize)]
pub struct AliasDef {
    pub name: String,
    pub ty: String,
    pub doc: String,
}

#[derive(Debug, Deserialize)]
pub struct StructDef {
    pub name: String,
    pub doc: String,
    pub fields: Vec<OverrideField>,
}

#[derive(Debug, Deserialize)]
pub struct OverrideField {
    pub name: String,
    #[serde(default)]
    pub rust_name: Option<String>,
    pub ty: String,
    pub doc: String,
}

struct FieldIr {
    json_name: String,
    rust_name: String,
    ty: String,
    doc: String,
}

struct Index<'a> {
    structs: BTreeMap<&'a str, &'a StructDef>,
    aliases: BTreeMap<&'a str, &'a str>,
}

pub fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .canonicalize()
        .expect("workspace root")
}

pub fn load_overrides() -> Result<Overrides, String> {
    let text = fs::read_to_string(workspace_root().join("protocol/overrides.toml"))
        .map_err(|error| error.to_string())?;
    toml::from_str(&text).map_err(|error| error.to_string())
}

pub fn run(check: bool) -> Result<(), String> {
    let root = workspace_root();
    let protocol_text = fs::read_to_string(root.join("protocol/protocol.json"))
        .map_err(|error| error.to_string())?;
    let protocol: Protocol =
        serde_json::from_str(&protocol_text).map_err(|error| error.to_string())?;
    let overrides = load_overrides()?;
    let files = generate(&protocol, &overrides)?;
    let untyped = untyped_fields(&protocol, &overrides);
    if untyped.is_empty() {
        eprintln!("all object fields have overrides");
    } else {
        eprintln!("{} object fields still use JSON values:", untyped.len());
        for field in &untyped {
            eprintln!("  {field}");
        }
    }

    let staging = root.join("target/xtask-codegen");
    if staging.exists() {
        fs::remove_dir_all(&staging).map_err(|error| error.to_string())?;
    }
    for (relative, contents) in &files {
        let path = staging.join(relative);
        fs::create_dir_all(path.parent().unwrap()).map_err(|error| error.to_string())?;
        fs::write(&path, contents).map_err(|error| error.to_string())?;
    }
    rustfmt(files.keys().map(|relative| staging.join(relative)))?;

    let mut stale = Vec::new();
    for relative in files.keys() {
        let formatted =
            fs::read_to_string(staging.join(relative)).map_err(|error| error.to_string())?;
        let destination = root.join(relative);
        if check {
            let existing = fs::read_to_string(&destination).unwrap_or_default();
            if normalize(&existing) != normalize(&formatted) {
                stale.push(relative.clone());
            }
        } else {
            if let Some(parent) = destination.parent() {
                fs::create_dir_all(parent).map_err(|error| error.to_string())?;
            }
            fs::write(&destination, formatted).map_err(|error| error.to_string())?;
        }
    }
    if !stale.is_empty() {
        return Err(format!(
            "generated sources are stale ({}); run cargo xtask codegen",
            stale.join(", ")
        ));
    }
    Ok(())
}

pub fn untyped_fields(protocol: &Protocol, overrides: &Overrides) -> Vec<String> {
    let mut missing = Vec::new();
    for request in &protocol.requests {
        consider(
            &mut missing,
            &overrides.fields,
            &request.request_type,
            "request",
            &request.request_fields,
        );
        consider(
            &mut missing,
            &overrides.fields,
            &request.request_type,
            "response",
            &request.response_fields,
        );
    }
    for event in &protocol.events {
        consider(
            &mut missing,
            &overrides.fields,
            &event.event_type,
            "data",
            &event.data_fields,
        );
    }
    missing.sort();
    missing
}

fn consider(
    missing: &mut Vec<String>,
    fields: &BTreeMap<String, String>,
    owner: &str,
    side: &str,
    protocol_fields: &[ProtocolField],
) {
    for field in protocol_fields {
        if !is_loose(&field.value_type) {
            continue;
        }
        let key = format!("{owner}.{side}.{}", field.value_name);
        if !fields.contains_key(&key) {
            missing.push(format!("{key} ({})", field.value_type));
        }
    }
}

fn is_loose(value_type: &str) -> bool {
    matches!(
        value_type,
        "Object" | "Any" | "Array<Object>" | "Array<Any>"
    )
}

fn generate(
    protocol: &Protocol,
    overrides: &Overrides,
) -> Result<BTreeMap<String, String>, String> {
    let index = Index {
        structs: overrides
            .structs
            .iter()
            .map(|item| (item.name.as_str(), item))
            .collect(),
        aliases: overrides
            .aliases
            .iter()
            .map(|item| (item.name.as_str(), item.ty.as_str()))
            .collect(),
    };
    let mut files = BTreeMap::new();
    files.insert(
        "crates/obs-websocket-core/src/generated/types.rs".into(),
        emit_types(overrides, &index),
    );
    files.insert(
        "crates/obs-websocket-core/src/generated/enums.rs".into(),
        emit_enums(&protocol.enums)?,
    );
    files.insert(
        "crates/obs-websocket-core/src/generated/events.rs".into(),
        emit_events(&protocol.events, overrides, &index),
    );

    let mut by_category: BTreeMap<String, Vec<&ProtocolRequest>> = BTreeMap::new();
    let mut seen = BTreeSet::new();
    for request in &protocol.requests {
        if !seen.insert(request.request_type.as_str()) {
            return Err(format!("duplicate request {}", request.request_type));
        }
        by_category
            .entry(module_name(&request.category))
            .or_default()
            .push(request);
    }
    let mut request_mods = String::from(HEADER);
    request_mods.push_str("//! Generated requests grouped by obs-websocket category.\n\n");
    for module in by_category.keys() {
        request_mods.push_str("mod ");
        request_mods.push_str(module);
        request_mods.push_str(";\npub use ");
        request_mods.push_str(module);
        request_mods.push_str("::*;\n");
    }
    files.insert(
        "crates/obs-websocket-core/src/generated/requests/mod.rs".into(),
        request_mods,
    );
    for (module, requests) in &by_category {
        files.insert(
            format!("crates/obs-websocket-core/src/generated/requests/{module}.rs"),
            emit_requests(requests, overrides, &index),
        );
    }

    let mut module = String::from(HEADER);
    module.push_str(
        "//! Generated OBS WebSocket types. Do not edit; run `cargo xtask codegen`.\n\npub mod enums;\npub mod events;\npub mod requests;\npub mod types;\n\n#[cfg(test)]\n#[allow(deprecated, clippy::unwrap_used, unused_imports)]\nmod roundtrip;\n\npub use enums::*;\npub use events::*;\npub use requests::*;\npub use types::*;\n",
    );
    files.insert(
        "crates/obs-websocket-core/src/generated/mod.rs".into(),
        module,
    );
    files.insert(
        "crates/obs-websocket-core/src/generated/roundtrip.rs".into(),
        emit_roundtrip(overrides, &protocol.requests, &protocol.events, &index),
    );
    files.insert(
        "crates/obs-websocket/src/generated/mod.rs".into(),
        format!("{HEADER}//! Generated category methods.\n\nmod api;\npub use api::*;\n"),
    );
    files.insert(
        "crates/obs-websocket/src/generated/api.rs".into(),
        emit_api(&by_category),
    );
    Ok(files)
}

fn emit_types(overrides: &Overrides, index: &Index<'_>) -> String {
    let mut out = String::from(HEADER);
    out.push_str("//! Structured objects supplied by `protocol/overrides.toml`.\n\nuse alloc::string::String;\nuse alloc::vec::Vec;\n\nuse serde::{Deserialize, Serialize};\n\n");
    for alias in &overrides.aliases {
        out.push_str(&rust_doc(&alias.doc));
        out.push_str("pub type ");
        out.push_str(&alias.name);
        out.push_str(" = ");
        out.push_str(&alias.ty);
        out.push_str(";\n\n");
    }
    for item in &overrides.structs {
        let fields = override_fields(item);
        out.push_str(&emit_struct(&item.name, &item.doc, false, &fields, index));
    }
    out
}

fn emit_requests(
    requests: &[&ProtocolRequest],
    overrides: &Overrides,
    index: &Index<'_>,
) -> String {
    let mut out = String::from(HEADER);
    out.push_str("#![allow(unused_imports)]\nuse alloc::string::String;\nuse alloc::vec::Vec;\n\nuse serde::{Deserialize, Serialize};\n\nuse crate::generated::types::*;\nuse crate::request::Request;\n\n");
    for request in requests {
        let request_fields = protocol_fields(
            &request.request_type,
            "request",
            &request.request_fields,
            overrides,
        );
        let response_name = format!("{}Response", request.request_type);
        let response_fields = protocol_fields(
            &request.request_type,
            "response",
            &request.response_fields,
            overrides,
        );
        let response_doc = format!("Response data for [`{}`].", request.request_type);
        out.push_str(&emit_struct(
            &request.request_type,
            &request_doc(request),
            request.deprecated,
            &request_fields,
            index,
        ));
        out.push_str(&emit_struct(
            &response_name,
            &response_doc,
            false,
            &response_fields,
            index,
        ));
        if request.deprecated {
            out.push_str("#[allow(deprecated)]\n");
        }
        out.push_str("impl Request for ");
        out.push_str(&request.request_type);
        out.push_str(" {\n    const REQUEST_TYPE: &'static str = \"");
        out.push_str(&request.request_type);
        out.push_str("\";\n    const INITIAL_VERSION: &'static str = \"");
        out.push_str(&request.initial_version);
        out.push_str("\";\n    const RPC_VERSION: &'static str = \"");
        out.push_str(&request.rpc_version);
        out.push_str("\";\n    type Response = ");
        out.push_str(&response_name);
        out.push_str(";\n}\n\n");
    }
    out
}

fn emit_events(events: &[ProtocolEvent], overrides: &Overrides, index: &Index<'_>) -> String {
    let mut out = String::from(HEADER);
    out.push_str("//! Generated events.\n\nuse alloc::string::{String, ToString};\nuse alloc::vec::Vec;\n\nuse serde::de::DeserializeOwned;\nuse serde::{Deserialize, Serialize};\nuse serde_json::Value;\n\nuse super::types::*;\n\n/// A typed event payload.\npub trait EventPayload: DeserializeOwned {\n    /// Protocol `eventType`.\n    const EVENT_TYPE: &'static str;\n    /// Borrows this payload when `event` is the matching variant.\n    fn from_event(event: &Event) -> Option<&Self>;\n}\n\n");
    for event in events {
        let fields = protocol_fields(&event.event_type, "data", &event.data_fields, overrides);
        out.push_str(&emit_struct(
            &event.event_type,
            &event_doc(event),
            event.deprecated,
            &fields,
            index,
        ));
        out.push_str("impl EventPayload for ");
        out.push_str(&event.event_type);
        out.push_str(" {\n    const EVENT_TYPE: &'static str = \"");
        out.push_str(&event.event_type);
        out.push_str("\";\n    fn from_event(event: &Event) -> Option<&Self> {\n        match event {\n            Event::");
        out.push_str(&event.event_type);
        out.push_str(
            "(payload) => Some(payload),\n            _ => None,\n        }\n    }\n}\n\n",
        );
    }
    out.push_str("/// An OBS WebSocket event.\n///\n/// Unknown `eventType` values are preserved so a newer server does not break an older client.\n#[derive(Debug, Clone, PartialEq)]\n#[non_exhaustive]\npub enum Event {\n");
    for event in events {
        out.push_str("    /// `");
        out.push_str(&event.event_type);
        out.push_str("`.\n    ");
        out.push_str(&event.event_type);
        out.push('(');
        out.push_str(&event.event_type);
        out.push_str("),\n");
    }
    out.push_str("    /// An event this build does not know.\n    Unknown {\n        /// Raw `eventType`.\n        event_type: String,\n        /// Raw `eventData`.\n        event_data: Value,\n    },\n}\n\nimpl Event {\n    /// Protocol name of this event.\n    pub fn event_type(&self) -> &str {\n        match self {\n");
    for event in events {
        out.push_str("            Self::");
        out.push_str(&event.event_type);
        out.push_str("(_) => \"");
        out.push_str(&event.event_type);
        out.push_str("\",\n");
    }
    out.push_str("            Self::Unknown { event_type, .. } => event_type,\n        }\n    }\n\n    /// Builds an event from `eventType` and `eventData`.\n    pub fn from_parts(event_type: &str, event_data: Value) -> Result<Self, serde_json::Error> {\n        let event_data = if event_data.is_null() {\n            Value::Object(serde_json::Map::new())\n        } else {\n            event_data\n        };\n        match event_type {\n");
    for event in events {
        out.push_str("            \"");
        out.push_str(&event.event_type);
        out.push_str("\" => Ok(Self::");
        out.push_str(&event.event_type);
        out.push_str("(serde_json::from_value(event_data)?)),\n");
    }
    out.push_str("            other => Ok(Self::Unknown {\n                event_type: other.to_string(),\n                event_data,\n            }),\n        }\n    }\n}\n");
    out
}

fn emit_api(by_category: &BTreeMap<String, Vec<&ProtocolRequest>>) -> String {
    let mut out = String::from(HEADER);
    out.push_str("//! Category-scoped methods over [`crate::Client::request`].\n\nuse obs_websocket_core::requests::*;\n\n");
    for (module, requests) in by_category {
        let type_name = pascal(module);
        out.push_str("/// Requests in the `");
        out.push_str(module);
        out.push_str("` category.\n#[derive(Debug, Clone, Copy)]\npub struct ");
        out.push_str(&type_name);
        out.push_str("<'a> {\n    client: &'a crate::Client,\n}\n\nimpl crate::Client {\n    /// Requests in the `");
        out.push_str(module);
        out.push_str("` category.\n    pub fn ");
        out.push_str(&raw_ident(module));
        out.push_str("(&self) -> ");
        out.push_str(&type_name);
        out.push_str("<'_> {\n        ");
        out.push_str(&type_name);
        out.push_str(" { client: self }\n    }\n}\n\nimpl ");
        out.push_str(&type_name);
        out.push_str("<'_> {\n");
        for request in requests {
            let method = raw_ident(&snake(&request.request_type));
            let response_empty = request.response_fields.is_empty();
            let request_empty = request.request_fields.is_empty();
            out.push_str(&rust_doc(&request_doc(request)).replace('\n', "\n    "));
            if request.deprecated {
                out.push_str("    #[allow(deprecated)]\n    #[deprecated(note = \"deprecated by obs-websocket\")]\n");
            }
            out.push_str("    pub async fn ");
            out.push_str(&method);
            out.push_str("(&self");
            if !request_empty {
                out.push_str(", request: &");
                out.push_str(&request.request_type);
            }
            out.push_str(") -> Result<");
            if response_empty {
                out.push_str("()");
            } else {
                out.push_str(&request.request_type);
                out.push_str("Response");
            }
            out.push_str(", crate::Error> {\n        ");
            if response_empty {
                out.push_str("self.client.request(");
                if request_empty {
                    out.push('&');
                    out.push_str(&request.request_type);
                    out.push_str("::new()");
                } else {
                    out.push_str("request");
                }
                out.push_str(").await?;\n        Ok(())\n");
            } else {
                out.push_str("self.client.request(");
                if request_empty {
                    out.push('&');
                    out.push_str(&request.request_type);
                    out.push_str("::new()");
                } else {
                    out.push_str("request");
                }
                out.push_str(").await\n");
            }
            out.push_str("    }\n");
        }
        out.push_str("}\n\n");
    }
    out
}

fn emit_roundtrip(
    overrides: &Overrides,
    requests: &[ProtocolRequest],
    events: &[ProtocolEvent],
    index: &Index<'_>,
) -> String {
    let mut out = String::from(HEADER);
    out.push_str(
        "use alloc::string::{String, ToString};\nuse alloc::vec::Vec;\n\nuse super::*;\n\n",
    );
    for item in &overrides.structs {
        let fields = override_fields(item);
        out.push_str(&sample_fn(&item.name, &fields, index));
        out.push_str(&roundtrip_fn(&item.name, &fields));
    }
    for request in requests {
        let fields = protocol_fields(
            &request.request_type,
            "request",
            &request.request_fields,
            overrides,
        );
        out.push_str(&sample_fn(&request.request_type, &fields, index));
        out.push_str(&roundtrip_fn(&request.request_type, &fields));
        let response = format!("{}Response", request.request_type);
        let fields = protocol_fields(
            &request.request_type,
            "response",
            &request.response_fields,
            overrides,
        );
        out.push_str(&sample_fn(&response, &fields, index));
        out.push_str(&roundtrip_fn(&response, &fields));
    }
    for event in events {
        let fields = protocol_fields(&event.event_type, "data", &event.data_fields, overrides);
        let function = snake(&event.event_type);
        out.push_str(&sample_fn(&event.event_type, &fields, index));
        out.push_str(&roundtrip_fn(&event.event_type, &fields));
        out.push_str("#[test]\nfn event_parts_");
        out.push_str(&function);
        out.push_str("() {\n    let value = sample_");
        out.push_str(&function);
        out.push_str("();\n    let event = Event::from_parts(\"");
        out.push_str(&event.event_type);
        out.push_str("\", serde_json::to_value(&value).unwrap()).unwrap();\n    assert_eq!(event.event_type(), \"");
        out.push_str(&event.event_type);
        out.push_str("\");\n}\n\n");
    }
    out
}

fn emit_enums(enums: &[ProtocolEnum]) -> Result<String, String> {
    let mut out = String::from(HEADER);
    out.push_str("//! Generated enumerations.\n\nuse alloc::string::{String, ToString};\n\nuse serde::{Deserialize, Serialize};\n\n");
    for item in enums {
        if item.enum_type == "EventSubscription" {
            out.push_str(&emit_subscriptions(item)?);
        } else if item
            .enum_identifiers
            .iter()
            .all(|id| parse_i64(&id.enum_value).is_some())
        {
            out.push_str(&emit_numeric(item));
        } else {
            out.push_str(&emit_strings(item));
        }
    }
    Ok(out)
}

fn emit_subscriptions(item: &ProtocolEnum) -> Result<String, String> {
    let mut known = BTreeMap::new();
    let mut flags = Vec::new();
    let mut all_names = Vec::new();
    for identifier in &item.enum_identifiers {
        let value = eval_bits(&identifier.enum_value, &known).ok_or_else(|| {
            format!(
                "cannot evaluate EventSubscription::{}",
                identifier.enum_identifier
            )
        })?;
        known.insert(identifier.enum_identifier.clone(), value);
        let rendered = identifier.enum_value.as_str().unwrap_or("");
        if rendered.contains('|') {
            all_names = rendered
                .split('|')
                .map(|part| {
                    part.trim()
                        .trim_matches(|c| c == '(' || c == ')')
                        .to_string()
                })
                .filter(|part| !part.is_empty())
                .collect();
            continue;
        }
        if value == 0 {
            continue;
        }
        flags.push((
            identifier.enum_identifier.clone(),
            value,
            identifier.description.clone(),
            identifier.deprecated,
        ));
    }
    let mut out = String::new();
    out.push_str("bitflags::bitflags! {\n    /// Event subscription bitset sent in `Identify` and `Reidentify`.\n    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n    pub struct EventSubscription: u32 {\n");
    for (name, value, doc, deprecated) in &flags {
        for line in rust_doc(doc).lines() {
            out.push_str("        ");
            out.push_str(line);
            out.push('\n');
        }
        if *deprecated {
            out.push_str("        #[deprecated(note = \"deprecated by obs-websocket\")]\n");
        }
        out.push_str("        const ");
        out.push_str(name);
        out.push_str(" = ");
        out.push_str(&value.to_string());
        out.push_str(";\n");
    }
    out.push_str("    }\n}\n\nimpl EventSubscription {\n    /// Protocol value `None`: subscribe to nothing.\n    pub const NONE: Self = Self::empty();\n    /// Non-high-volume events. Protocol value `All`.\n    pub const ALL: Self = Self::empty()");
    for name in &all_names {
        out.push_str("\n        .union(Self::");
        out.push_str(name);
        out.push(')');
    }
    out.push_str(";\n}\n\nimpl Serialize for EventSubscription {\n    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {\n        serializer.serialize_u32(self.bits())\n    }\n}\n\nimpl<'de> Deserialize<'de> for EventSubscription {\n    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {\n        let bits = u32::deserialize(deserializer)?;\n        Ok(Self::from_bits_truncate(bits))\n    }\n}\n\n");
    let _ = item;
    Ok(out)
}

fn emit_numeric(item: &ProtocolEnum) -> String {
    let (rust_ty, from_name, as_name, ser) = match item.enum_type.as_str() {
        "WebSocketOpCode" => ("u8", "from_u8", "as_u8", "u8"),
        "WebSocketCloseCode" => ("u16", "from_u16", "as_u16", "u16"),
        _ => ("i64", "from_i64", "as_i64", "i64"),
    };
    let mut out = String::new();
    out.push_str(&rust_doc(&format!("`{}`.", item.enum_type)));
    out.push_str(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n#[non_exhaustive]\npub enum ",
    );
    out.push_str(&item.enum_type);
    out.push_str(" {\n");
    for identifier in &item.enum_identifiers {
        out.push_str(&indent_doc(&identifier.description));
        if identifier.deprecated {
            out.push_str("    #[deprecated(note = \"deprecated by obs-websocket\")]\n");
        }
        out.push_str("    ");
        out.push_str(&variant_ident(&identifier.enum_identifier));
        out.push_str(",\n");
    }
    out.push_str("    /// A value introduced by a newer obs-websocket build.\n    Other(");
    out.push_str(rust_ty);
    out.push_str("),\n}\n\nimpl ");
    out.push_str(&item.enum_type);
    out.push_str(" {\n    /// Maps a protocol number, preserving unknown values.\n    pub fn ");
    out.push_str(from_name);
    out.push_str("(code: ");
    out.push_str(rust_ty);
    out.push_str(") -> Self {\n        match code {\n");
    for identifier in &item.enum_identifiers {
        let code = parse_i64(&identifier.enum_value).unwrap_or(0);
        out.push_str("            ");
        out.push_str(&code.to_string());
        out.push_str(" => Self::");
        out.push_str(&variant_ident(&identifier.enum_identifier));
        out.push_str(",\n");
    }
    out.push_str("            other => Self::Other(other),\n        }\n    }\n\n    /// Protocol number.\n    pub fn ");
    out.push_str(as_name);
    out.push_str("(self) -> ");
    out.push_str(rust_ty);
    out.push_str(" {\n        match self {\n");
    for identifier in &item.enum_identifiers {
        let code = parse_i64(&identifier.enum_value).unwrap_or(0);
        out.push_str("            Self::");
        out.push_str(&variant_ident(&identifier.enum_identifier));
        out.push_str(" => ");
        out.push_str(&code.to_string());
        out.push_str(",\n");
    }
    out.push_str("            Self::Other(code) => code,\n        }\n    }\n}\n\n");
    out.push_str(&numeric_serde(&item.enum_type, ser, from_name, as_name));
    out
}

fn numeric_serde(name: &str, rust_ty: &str, from_name: &str, as_name: &str) -> String {
    format!(
        "impl Serialize for {name} {{\n    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {{\n        serializer.serialize_{rust_ty}(self.{as_name}())\n    }}\n}}\n\nimpl<'de> Deserialize<'de> for {name} {{\n    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {{\n        Ok(Self::{from_name}({rust_ty}::deserialize(deserializer)?))\n    }}\n}}\n\n"
    )
}

fn emit_strings(item: &ProtocolEnum) -> String {
    let mut out = String::new();
    out.push_str(&rust_doc(&format!("`{}`.", item.enum_type)));
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Hash)]\n#[non_exhaustive]\npub enum ");
    out.push_str(&item.enum_type);
    out.push_str(" {\n");
    for identifier in &item.enum_identifiers {
        out.push_str(&indent_doc(&identifier.description));
        if identifier.deprecated {
            out.push_str("    #[deprecated(note = \"deprecated by obs-websocket\")]\n");
        }
        out.push_str("    ");
        out.push_str(&variant_ident(&identifier.enum_identifier));
        out.push_str(",\n");
    }
    out.push_str("    /// A value introduced by a newer obs-websocket build.\n    Other(String),\n}\n\nimpl ");
    out.push_str(&item.enum_type);
    out.push_str(" {\n    /// Parses a protocol string, preserving unknown values.\n    pub fn parse(value: &str) -> Self {\n        match value {\n");
    for identifier in &item.enum_identifiers {
        let raw = identifier
            .enum_value
            .as_str()
            .unwrap_or(&identifier.enum_identifier);
        out.push_str("            \"");
        out.push_str(raw);
        out.push_str("\" => Self::");
        out.push_str(&variant_ident(&identifier.enum_identifier));
        out.push_str(",\n");
    }
    out.push_str("            other => Self::Other(other.to_string()),\n        }\n    }\n\n    /// Protocol string.\n    pub fn as_str(&self) -> &str {\n        match self {\n");
    for identifier in &item.enum_identifiers {
        let raw = identifier
            .enum_value
            .as_str()
            .unwrap_or(&identifier.enum_identifier);
        out.push_str("            Self::");
        out.push_str(&variant_ident(&identifier.enum_identifier));
        out.push_str(" => \"");
        out.push_str(raw);
        out.push_str("\",\n");
    }
    out.push_str(
        "            Self::Other(value) => value,\n        }\n    }\n}\n\nimpl Serialize for ",
    );
    out.push_str(&item.enum_type);
    out.push_str(" {\n    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {\n        serializer.serialize_str(self.as_str())\n    }\n}\n\nimpl<'de> Deserialize<'de> for ");
    out.push_str(&item.enum_type);
    out.push_str(" {\n    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {\n        Ok(Self::parse(&String::deserialize(deserializer)?))\n    }\n}\n\n");
    out
}

fn emit_struct(
    name: &str,
    doc: &str,
    deprecated: bool,
    fields: &[FieldIr],
    index: &Index<'_>,
) -> String {
    let mut out = String::new();
    out.push_str(&rust_doc(doc));
    if deprecated {
        out.push_str("#[deprecated(note = \"deprecated by obs-websocket\")]\n");
    }
    out.push_str("#[derive(Debug, Clone, PartialEq");
    if !fields.iter().any(|field| has_float(&field.ty, index)) {
        out.push_str(", Eq");
    }
    out.push_str(", Serialize, Deserialize");
    if fields.is_empty() || fields.iter().all(|field| field.ty.starts_with("Option<")) {
        out.push_str(", Default");
    }
    out.push_str(")]\n#[non_exhaustive]\npub struct ");
    out.push_str(name);
    out.push_str(" {\n");
    for field in fields {
        out.push_str(&indent_doc(&field.doc));
        out.push_str("    #[serde(rename = \"");
        out.push_str(&field.json_name);
        out.push('"');
        if field.ty.starts_with("Option<") {
            out.push_str(", default, skip_serializing_if = \"Option::is_none\"");
        }
        out.push_str(")]\n    pub ");
        out.push_str(&field.rust_name);
        out.push_str(": ");
        out.push_str(&field.ty);
        out.push_str(",\n");
    }
    out.push_str("}\n\n");
    out.push_str(&emit_builder(name, fields));
    out.push('\n');
    out
}

fn emit_builder(name: &str, fields: &[FieldIr]) -> String {
    let mut out = String::new();
    out.push_str("impl ");
    out.push_str(name);
    out.push_str(" {\n    /// Creates a value.\n    #[must_use]\n    pub fn new(");
    let required: Vec<&FieldIr> = fields
        .iter()
        .filter(|field| !field.ty.starts_with("Option<"))
        .collect();
    for (position, field) in required.iter().enumerate() {
        if position > 0 {
            out.push_str(", ");
        }
        out.push_str(&field.rust_name);
        out.push_str(": ");
        out.push_str(&param_ty(&field.ty));
    }
    out.push_str(") -> Self {\n        Self {\n");
    for field in fields {
        out.push_str("            ");
        out.push_str(&field.rust_name);
        out.push_str(": ");
        if field.ty.starts_with("Option<") {
            out.push_str("None");
        } else if field.ty == "String" {
            out.push_str(&field.rust_name);
            out.push_str(".into()");
        } else {
            out.push_str(&field.rust_name);
        }
        out.push_str(",\n");
    }
    out.push_str("        }\n    }\n");
    for field in fields
        .iter()
        .filter(|field| field.ty.starts_with("Option<"))
    {
        let inner = unwrap_angle("Option", &field.ty);
        out.push_str("    /// Sets `");
        out.push_str(&field.json_name);
        out.push_str("`.\n    #[must_use]\n    pub fn ");
        out.push_str(&field.rust_name);
        out.push_str("(mut self, value: ");
        out.push_str(&param_ty(inner));
        out.push_str(") -> Self {\n        self.");
        out.push_str(&field.rust_name);
        out.push_str(" = Some(");
        if inner == "String" {
            out.push_str("value.into()");
        } else {
            out.push_str("value");
        }
        out.push_str(");\n        self\n    }\n");
    }
    out.push_str("}\n");
    out
}

fn protocol_fields(
    owner: &str,
    side: &str,
    fields: &[ProtocolField],
    overrides: &Overrides,
) -> Vec<FieldIr> {
    fields
        .iter()
        .filter(|field| !field.value_name.contains('.'))
        .map(|field| {
            let key = format!("{owner}.{side}.{}", field.value_name);
            let ty = if let Some(overridden) = overrides.fields.get(&key) {
                overridden.clone()
            } else {
                map_type(
                    &field.value_name,
                    &field.value_type,
                    field.value_optional || nullable(&field.value_description),
                )
            };
            FieldIr {
                json_name: field.value_name.clone(),
                rust_name: snake(&field.value_name),
                ty,
                doc: field_doc(field),
            }
        })
        .collect()
}

fn override_fields(item: &StructDef) -> Vec<FieldIr> {
    item.fields
        .iter()
        .map(|field| FieldIr {
            json_name: field.name.clone(),
            rust_name: field
                .rust_name
                .clone()
                .unwrap_or_else(|| snake(&field.name)),
            ty: field.ty.clone(),
            doc: field.doc.clone(),
        })
        .collect()
}

fn map_type(name: &str, value_type: &str, optional: bool) -> String {
    let base = match value_type {
        "String" => "String",
        "Boolean" => "bool",
        "Number" if FLOAT_FIELDS.contains(&name) => "f64",
        "Number" => "i64",
        "Object" | "Any" => "serde_json::Value",
        "Array<String>" => "Vec<String>",
        "Array<Boolean>" => "Vec<bool>",
        "Array<Number>" if FLOAT_FIELDS.contains(&name) => "Vec<f64>",
        "Array<Number>" => "Vec<i64>",
        "Array<Object>" | "Array<Any>" => "Vec<serde_json::Value>",
        _ => "serde_json::Value",
    };
    if optional {
        format!("Option<{base}>")
    } else {
        base.to_string()
    }
}

fn nullable(description: &str) -> bool {
    description.contains("`null`")
}

fn field_doc(field: &ProtocolField) -> String {
    let mut doc = field.value_description.clone();
    if let Some(restrictions) = &field.value_restrictions {
        if !doc.is_empty() {
            doc.push(' ');
        }
        doc.push_str("Restrictions: ");
        doc.push_str(restrictions);
        doc.push('.');
    }
    if let Some(behavior) = &field.value_optional_behavior {
        if !behavior.is_empty() && behavior != "N/A" && behavior != "Unknown" && behavior != "None"
        {
            if !doc.is_empty() {
                doc.push(' ');
            }
            doc.push_str("When omitted: ");
            doc.push_str(behavior);
            doc.push('.');
        }
    }
    if doc.is_empty() {
        field.value_name.clone()
    } else {
        doc
    }
}

fn request_doc(request: &ProtocolRequest) -> String {
    format!(
        "{}\n\n- Request type: `{}`\n- Category: `{}`\n- Initial version: {}\n- RPC version: {}",
        request.description.trim(),
        request.request_type,
        request.category,
        request.initial_version,
        request.rpc_version
    )
}

fn event_doc(event: &ProtocolEvent) -> String {
    format!(
        "{}\n\n- Event type: `{}`\n- Subscription: `{}`\n- Category: `{}`\n- Initial version: {}",
        event.description.trim(),
        event.event_type,
        event.event_subscription,
        event.category,
        event.initial_version
    )
}

fn sample_fn(name: &str, fields: &[FieldIr], index: &Index<'_>) -> String {
    let mut out = format!("fn sample_{}() -> {name} {{\n    {name} {{\n", snake(name));
    for field in fields {
        out.push_str("        ");
        out.push_str(&field.rust_name);
        out.push_str(": ");
        out.push_str(&sample_expr(&field.ty, index));
        out.push_str(",\n");
    }
    out.push_str("    }\n}\n\n");
    out
}

fn roundtrip_fn(name: &str, fields: &[FieldIr]) -> String {
    let mut out = format!(
        "#[test]\nfn roundtrip_{}() {{\n    let value = sample_{}();\n    let json = serde_json::to_value(&value).unwrap();\n",
        snake(name),
        snake(name)
    );
    for field in fields {
        if !field.ty.starts_with("Option<") {
            out.push_str("    assert!(json.get(\"");
            out.push_str(&field.json_name);
            out.push_str("\").is_some());\n");
        }
    }
    out.push_str("    let back: ");
    out.push_str(name);
    out.push_str(" = serde_json::from_value(json).unwrap();\n    assert_eq!(value, back);\n}\n\n");
    out
}

fn sample_expr(ty: &str, index: &Index<'_>) -> String {
    if let Some(inner) = ty
        .strip_prefix("Option<")
        .and_then(|rest| rest.strip_suffix('>'))
    {
        let _ = inner;
        return "None".into();
    }
    if ty
        .strip_prefix("Vec<")
        .and_then(|rest| rest.strip_suffix('>'))
        .is_some()
    {
        return "Vec::new()".into();
    }
    match ty {
        "String" => "\"sample\".to_string()".into(),
        "bool" => "false".into(),
        "i64" => "0".into(),
        "f64" => "0.0".into(),
        "serde_json::Value" => "serde_json::Value::Null".into(),
        other if index.structs.contains_key(other) => format!("sample_{}()", snake(other)),
        other if index.aliases.contains_key(other) => {
            format!("<{other} as core::default::Default>::default()")
        }
        other => format!("compile_error!(\"no sample for {other}\")"),
    }
}

fn has_float(ty: &str, index: &Index<'_>) -> bool {
    if ty.contains("f64") {
        return true;
    }
    let mut current = ty.to_string();
    loop {
        if let Some(inner) = unwrap_known(&current) {
            current = inner;
            continue;
        }
        break;
    }
    if let Some(item) = index.structs.get(current.as_str()) {
        return item.fields.iter().any(|field| has_float(&field.ty, index));
    }
    if let Some(alias) = index.aliases.get(current.as_str()) {
        return alias.contains("f64");
    }
    false
}

fn unwrap_known(ty: &str) -> Option<String> {
    for wrapper in ["Option", "Vec"] {
        if let Some(inner) = ty.strip_prefix(&format!("{wrapper}<")) {
            if let Some(inner) = inner.strip_suffix('>') {
                if !inner.contains('<') {
                    return Some(inner.to_string());
                }
            }
        }
    }
    None
}

fn unwrap_angle<'a>(wrapper: &str, ty: &'a str) -> &'a str {
    ty.strip_prefix(&format!("{wrapper}<"))
        .and_then(|rest| rest.strip_suffix('>'))
        .unwrap_or(ty)
}

fn param_ty(ty: &str) -> String {
    if ty == "String" {
        "impl Into<String>".into()
    } else {
        ty.to_string()
    }
}

fn rust_doc(text: &str) -> String {
    let mut out = String::new();
    let cleaned = text.replace('\r', "");
    let source = if cleaned.trim().is_empty() {
        "Generated."
    } else {
        cleaned.trim()
    };
    for line in source.split('\n') {
        out.push_str("/// ");
        out.push_str(&escape_doc(line.trim_end()));
        out.push('\n');
    }
    out
}

fn indent_doc(text: &str) -> String {
    rust_doc(text)
        .lines()
        .map(|line| format!("    {line}\n"))
        .collect()
}

fn escape_doc(line: &str) -> String {
    line.replace("*/", "* /")
        .replace('[', "\\[")
        .replace(']', "\\]")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn module_name(category: &str) -> String {
    raw_ident(&category.to_ascii_lowercase().replace([' ', '-'], "_"))
}

fn pascal(snake_name: &str) -> String {
    snake_name
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

fn snake(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    raw_ident(&out)
}

fn variant_ident(ident: &str) -> String {
    let trimmed = ident.strip_prefix("OBS_WEBSOCKET_").unwrap_or(ident);
    let pascal_name = if trimmed.contains('_') {
        pascal(&trimmed.to_ascii_lowercase())
    } else {
        trimmed.to_string()
    };
    raw_ident(&pascal_name)
}

fn raw_ident(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "false", "fn", "for", "gen", "if", "impl", "in", "let", "loop", "match", "mod",
        "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct", "super",
        "trait", "true", "try", "type", "unsafe", "use", "where", "abstract", "become", "box",
        "do", "final", "macro", "override", "priv", "typeof", "unsized", "virtual", "yield",
    ];
    if KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

fn parse_i64(value: &Value) -> Option<i64> {
    match value {
        Value::Number(number) => number
            .as_i64()
            .or_else(|| number.as_u64().map(|value| value as i64)),
        Value::String(text) => eval_bits(value, &BTreeMap::new())
            .map(|value| value as i64)
            .or_else(|| text.parse().ok()),
        _ => None,
    }
}

fn eval_bits(value: &Value, known: &BTreeMap<String, u32>) -> Option<u32> {
    match value {
        Value::Number(number) => number.as_u64().map(|value| value as u32),
        Value::String(text) => eval_expr(text.trim(), known),
        _ => None,
    }
}

fn eval_expr(expr: &str, known: &BTreeMap<String, u32>) -> Option<u32> {
    let expr = expr.trim().trim_matches(|ch| ch == '(' || ch == ')').trim();
    if let Some(rest) = expr.strip_prefix("1 << ") {
        let bits: u32 = rest.trim().parse().ok()?;
        return Some(1u32 << bits);
    }
    if expr.contains('|') {
        let mut acc = 0u32;
        for part in expr.split('|') {
            acc |= eval_expr(part.trim(), known)?;
        }
        return Some(acc);
    }
    if let Ok(number) = expr.parse::<u32>() {
        return Some(number);
    }
    known.get(expr).copied()
}

fn rustfmt(paths: impl Iterator<Item = PathBuf>) -> Result<(), String> {
    let paths: Vec<PathBuf> = paths.collect();
    if paths.is_empty() {
        return Ok(());
    }
    let status = Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .args(&paths)
        .status()
        .map_err(|error| format!("rustfmt: {error}"))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("rustfmt exited with {status}"))
    }
}

fn normalize(text: &str) -> String {
    text.replace("\r\n", "\n")
}

#[cfg(test)]
mod tests {
    use super::{map_type, nullable, snake};

    #[test]
    fn snake_case_splits_capitals() {
        assert_eq!(snake("GetSceneList"), "get_scene_list");
        assert_eq!(snake("sceneUuid"), "scene_uuid");
    }

    #[test]
    fn null_in_backticks_becomes_optional() {
        assert!(nullable("Can be `null` if studio mode is off"));
        assert!(!nullable("Name of the scene"));
        assert_eq!(map_type("sceneName", "String", true), "Option<String>");
        assert_eq!(map_type("inputVolumeDb", "Number", false), "f64");
        assert_eq!(map_type("sceneItemId", "Number", false), "i64");
    }
}
